on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.7'
      - name: Run Tests
        run: make test
